FROM docker.io/mysql:8

COPY conf.d/mysql_native_password.cnf /etc/mysql/conf.d/mysql_native_password.cnf
COPY conf.d/secure_file_priv.cnf /etc/mysql/conf.d/secure_file_priv.cnf
COPY conf.d/sql_mode.cnf /etc/mysql/conf.d/sql_mode.cnf
